-   <div>

    ---
    title: "Mario_kart_analysis"
    format: html
    editor: visual
    ---

    </div>

We're importing the dataset from the Mario Kart

```{r}
options(digits = 5)

```

```{r, echo = FALSE}
library(tidyverse)
library(knitr)
library(openintro)
library(readr)
```

#This is our boxplot

```{r}
mariokart |>
  ggplot(aes(x=cond, y=total_pr, color=cond)) +  
  geom_boxplot() +
  coord_flip() +
  scale_color_brewer(palette = "Set1", direction = -1)

```

```{r}
mario_kart_selected <-
  mariokart |>
  select(id, cond, total_pr) 

mario_kart_selected <-
  arrange(mario_kart_selected,desc(total_pr))
  

used_mariokart <-
  mario_kart_selected |>
  filter(cond=="used") 


used_mariokart <-
   filter(used_mariokart, !(total_pr %in% c(326.51, 118.5))) 

used_mariokart<-
   arrange(used_mariokart,desc(total_pr))
  
new_mariokart <-
  mario_kart_selected |>
  filter(cond== "new") 

new_mariokart <-
  arrange(new_mariokart,desc(total_pr)) 

```

Interquartile

#Here we removed the outliers. We removed the outliers which are 326.51, and 118.5

```{r}
mario_kart_selected <-
    filter(mario_kart_selected, !(total_pr %in% c(326.51, 118.5)))
```

#This is our mean by group

```{r}
mean_by_group <- mario_kart_selected |>
  group_by(cond) |>
  summarise(mean_value = mean(total_pr))

New_mean <-
  mean_by_group |>
  filter(cond == "new")

Used_mean <-
  mean_by_group |>
  filter(cond == "used")


print(mean_by_group)
```

#This is our T- Test for Mario Kart

```{r}
mario_kart_t_test<-
t.test(total_pr ~ cond, data = mario_kart_selected, alternative ="t")

mario_kart_t_test

```

```{r}
result_table <- data.frame(
  new_mean = New_mean$mean_value,
  used_mean = Used_mean$mean_value,
  t_Statistic = mario_kart_t_test$statistic,
  Degrees_of_Freedom = mario_kart_t_test$parameter,
  P_Value = mario_kart_t_test$p.value,
  Lower_CI_95 = mario_kart_t_test$conf.int[1],
  Upper_CI_95= mario_kart_t_test$conf.int[2]
)
result_table_formatted <- kable(result_table, caption = "Mario Kart T-Test Results by Used and New")

result_table_formatted

```

#N

```{r}
filter(mario_kart_selected, cond %in% c("new", "used"))|>
  group_by(cond) |>
  summarise(mean = mean(total_pr), 
            sd = sd(total_pr), 
            median = median(total_pr), 
            min = min(total_pr), 
            max = max(total_pr), 
            count = n()) |>
  kable(digits = 3, caption = "Summary Statistics of Mario Kart")
```
